import React, { Suspense } from "react";
import "./globals.css";
import { Header, NavBar, NavBarAdmin } from "./ui";
import Footer from "./ui/Footer";
import { ProviderRedux } from "@/Redux/Provider";
import { EstadoApp, User_Carrito } from "./Components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-neutral-100">
        <ProviderRedux>
          <Suspense fallback={"Cargando Estado APP"}>
            <EstadoApp />
          </Suspense>
          <User_Carrito />
          <Header />
          <NavBar />
          <NavBarAdmin />
          <div>{children}</div>
          <Footer />
        </ProviderRedux>
      </body>
    </html>
  );
}
