import React from "react";
import "./globals.css";
import { Header, NavBar, NavBarAdmin } from "./ui";
import Footer from "./ui/Footer";
import { ProviderRedux } from "@/Redux/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container mx-auto bg-neutral-100">
        <ProviderRedux>
          <Header />
          <NavBarAdmin />
          <NavBar />
          <div>{children}</div>
          <Footer />
        </ProviderRedux>
      </body>
    </html>
  );
}
